//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsClient.FirstServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://TestService.ZavPostav.AndrK/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TestService.ZavPostav.AndrK/", ConfigurationName="FirstServiceReference.FirstServiceSoap")]
    public interface FirstServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем HelloWorldResult из пространства имен http://TestService.ZavPostav.AndrK/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://TestService.ZavPostav.AndrK/HelloWorld", ReplyAction="*")]
        WebFormsClient.FirstServiceReference.HelloWorldResponse HelloWorld(WebFormsClient.FirstServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TestService.ZavPostav.AndrK/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsClient.FirstServiceReference.HelloWorldResponse> HelloWorldAsync(WebFormsClient.FirstServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем listInt из пространства имен http://TestService.ZavPostav.AndrK/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://TestService.ZavPostav.AndrK/Add", ReplyAction="*")]
        WebFormsClient.FirstServiceReference.AddResponse Add(WebFormsClient.FirstServiceReference.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TestService.ZavPostav.AndrK/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormsClient.FirstServiceReference.AddResponse> AddAsync(WebFormsClient.FirstServiceReference.AddRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://TestService.ZavPostav.AndrK/", Order=0)]
        public WebFormsClient.FirstServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebFormsClient.FirstServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://TestService.ZavPostav.AndrK/", Order=0)]
        public WebFormsClient.FirstServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebFormsClient.FirstServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TestService.ZavPostav.AndrK/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://TestService.ZavPostav.AndrK/", Order=0)]
        public WebFormsClient.FirstServiceReference.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(WebFormsClient.FirstServiceReference.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TestService.ZavPostav.AndrK/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormsClient.FirstServiceReference.ArrayOfInt listInt;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(WebFormsClient.FirstServiceReference.ArrayOfInt listInt) {
            this.listInt = listInt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://TestService.ZavPostav.AndrK/", Order=0)]
        public WebFormsClient.FirstServiceReference.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(WebFormsClient.FirstServiceReference.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TestService.ZavPostav.AndrK/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FirstServiceSoapChannel : WebFormsClient.FirstServiceReference.FirstServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstServiceSoapClient : System.ServiceModel.ClientBase<WebFormsClient.FirstServiceReference.FirstServiceSoap>, WebFormsClient.FirstServiceReference.FirstServiceSoap {
        
        public FirstServiceSoapClient() {
        }
        
        public FirstServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirstServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsClient.FirstServiceReference.HelloWorldResponse WebFormsClient.FirstServiceReference.FirstServiceSoap.HelloWorld(WebFormsClient.FirstServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebFormsClient.FirstServiceReference.HelloWorldRequest inValue = new WebFormsClient.FirstServiceReference.HelloWorldRequest();
            inValue.Body = new WebFormsClient.FirstServiceReference.HelloWorldRequestBody();
            WebFormsClient.FirstServiceReference.HelloWorldResponse retVal = ((WebFormsClient.FirstServiceReference.FirstServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsClient.FirstServiceReference.HelloWorldResponse> WebFormsClient.FirstServiceReference.FirstServiceSoap.HelloWorldAsync(WebFormsClient.FirstServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsClient.FirstServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WebFormsClient.FirstServiceReference.HelloWorldRequest inValue = new WebFormsClient.FirstServiceReference.HelloWorldRequest();
            inValue.Body = new WebFormsClient.FirstServiceReference.HelloWorldRequestBody();
            return ((WebFormsClient.FirstServiceReference.FirstServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormsClient.FirstServiceReference.AddResponse WebFormsClient.FirstServiceReference.FirstServiceSoap.Add(WebFormsClient.FirstServiceReference.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(WebFormsClient.FirstServiceReference.ArrayOfInt listInt) {
            WebFormsClient.FirstServiceReference.AddRequest inValue = new WebFormsClient.FirstServiceReference.AddRequest();
            inValue.Body = new WebFormsClient.FirstServiceReference.AddRequestBody();
            inValue.Body.listInt = listInt;
            WebFormsClient.FirstServiceReference.AddResponse retVal = ((WebFormsClient.FirstServiceReference.FirstServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormsClient.FirstServiceReference.AddResponse> WebFormsClient.FirstServiceReference.FirstServiceSoap.AddAsync(WebFormsClient.FirstServiceReference.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormsClient.FirstServiceReference.AddResponse> AddAsync(WebFormsClient.FirstServiceReference.ArrayOfInt listInt) {
            WebFormsClient.FirstServiceReference.AddRequest inValue = new WebFormsClient.FirstServiceReference.AddRequest();
            inValue.Body = new WebFormsClient.FirstServiceReference.AddRequestBody();
            inValue.Body.listInt = listInt;
            return ((WebFormsClient.FirstServiceReference.FirstServiceSoap)(this)).AddAsync(inValue);
        }
    }
}
