//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrK.ZavPostav.RepoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentData
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> specification_id { get; set; }
        public string fileName { get; set; }
        public byte[] content { get; set; }
    
        public virtual Specification Specification { get; set; }
    }
}
