//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrK.ZavPostav.RepoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheetTovarRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheetTovarRow()
        {
            this.ZavkaSellerRow = new HashSet<ZavkaSellerRow>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid scheet_id { get; set; }
        public int num { get; set; }
        public string articul { get; set; }
        public string name { get; set; }
        public Nullable<decimal> kol { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.Guid> oborudovanie_id { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
        public virtual ScheetTovar ScheetTovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZavkaSellerRow> ZavkaSellerRow { get; set; }
    }
}
