//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrK.ZavPostav.RepoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheetTovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheetTovar()
        {
            this.ScheetTovarRow = new HashSet<ScheetTovarRow>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public System.Guid seller_id { get; set; }
        public string num { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
        public Nullable<decimal> sum { get; set; }
        public Nullable<decimal> nds { get; set; }
        public bool isCompeted { get; set; }
    
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheetTovarRow> ScheetTovarRow { get; set; }
    }
}
