//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrK.ZavPostav.RepoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZavkaSeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZavkaSeller()
        {
            this.ZavkaSellerRow = new HashSet<ZavkaSellerRow>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public System.Guid seller_id { get; set; }
    
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZavkaSellerRow> ZavkaSellerRow { get; set; }
    }
}
