//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrK.ZavPostav.RepoSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gbItArch03Entities : DbContext
    {
        public gbItArch03Entities()
            : base("name=gbItArch03Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentData> DocumentData { get; set; }
        public virtual DbSet<Oborudovanie> Oborudovanie { get; set; }
        public virtual DbSet<ScheetTovar> ScheetTovar { get; set; }
        public virtual DbSet<ScheetTovarRow> ScheetTovarRow { get; set; }
        public virtual DbSet<Seller> Seller { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<Zakazchik> Zakazchik { get; set; }
        public virtual DbSet<ZakupDepartment> ZakupDepartment { get; set; }
        public virtual DbSet<ZavkaSeller> ZavkaSeller { get; set; }
        public virtual DbSet<ZavkaSellerRow> ZavkaSellerRow { get; set; }
        public virtual DbSet<ZavkaZakup> ZavkaZakup { get; set; }
        public virtual DbSet<ZavkaZakup_Oborudovanie> ZavkaZakup_Oborudovanie { get; set; }
    }
}
