//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrK.ZavPostav.MsSqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oborudovanie()
        {
            this.ScheetTovarRows = new HashSet<ScheetTovarRow>();
            this.Specifications = new HashSet<Specification>();
            this.ZavkaSellerRows = new HashSet<ZavkaSellerRow>();
            this.ZavkaZakup_Oborudovanie = new HashSet<ZavkaZakup_Oborudovanie>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string nomenklatura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheetTovarRow> ScheetTovarRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specification> Specifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZavkaSellerRow> ZavkaSellerRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZavkaZakup_Oborudovanie> ZavkaZakup_Oborudovanie { get; set; }
    }
}
