//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrK.ZavPostav.MsSqlRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gbItArch03Entities : DbContext
    {
        public gbItArch03Entities()
            : base("name=gbItArch03Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentData> DocumentDatas { get; set; }
        public virtual DbSet<Oborudovanie> Oborudovanies { get; set; }
        public virtual DbSet<ScheetTovar> ScheetTovars { get; set; }
        public virtual DbSet<ScheetTovarRow> ScheetTovarRows { get; set; }
        public virtual DbSet<SELLER> SELLERS { get; set; }
        public virtual DbSet<Specification> Specifications { get; set; }
        public virtual DbSet<ZAKAZCHIK> ZAKAZCHIKS { get; set; }
        public virtual DbSet<ZakupDepartment> ZakupDepartments { get; set; }
        public virtual DbSet<ZavkaSeller> ZavkaSellers { get; set; }
        public virtual DbSet<ZavkaSellerRow> ZavkaSellerRows { get; set; }
        public virtual DbSet<ZavkaZakup> ZavkaZakups { get; set; }
        public virtual DbSet<ZavkaZakup_Oborudovanie> ZavkaZakup_Oborudovanie { get; set; }
    }
}
